@todoId = 390be1cc-28aa-4deb-9bf6-2de481b27b2c
@host = http://localhost
@port = 5000
@url = {{host}}:{{port}}
###
GET {{url}} HTTP/1.1

##### Get Todos List
GET {{url}}/api/todo HTTP/1.1

#### Create Todo
POST {{url}}/api/todo HTTP/1.1
Content-Type: application/json

{
    "title":"Test03",
    "description":"Test Description"
}

### Get Todo By Id
GET {{url}}/api/todo/{{todoId}} HTTP/1.1

#### Update Todo
PATCH  {{url}}/api/todo/{{todoId}} HTTP/1.1
Content-Type: application/json

{
    "title":"Test02",
    "description":"Test Description02"
}

#### Delete Todo
DELETE {{url}}/api/todo/{{todoId}} HTTP/1.1


#### SignIn
POST {{url}}/api/todo/signin HTTP/1.1
Content-Type: application/json

{
    "username":"test01@test.com",
    "password":"password"
}

#### SignUp
POST {{url}}/api/todo/signup HTTP/1.1
Content-Type: application/json

{
    "username":"test01@test.com",
    "password":"password",
    "firstName":"Test",
    "lastName":"Test"
}

#### Logout
GET {{url}}/api/todo/logout HTTP/1.1